'use client'

import Header from '@/components/global/header/Header'
import './globals.css'
import { SessionProvider } from "next-auth/react"
import Sidebar from '@/components/global/sidebar/Sidebar'
import { createContext, useState } from 'react'
import { motion } from 'framer-motion'


 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const isLargeContext = createContext(true);


export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  
  const [isLarge , setIsLarge ] = useState(true);
  
  function toggle(){
    setIsLarge(!isLarge);
  }

  return (
    <html lang="en">
      <body className='w-screen h-screen'>
      <SessionProvider>
        <isLargeContext.Provider value={isLarge}>
        <Header isLarge={isLarge} change={toggle}/>
        <Sidebar isLarge={isLarge}/>
        <motion.div layout transition={{duration : 0.5}} className={`${isLarge ? 'md:pl-[16%]' : 'md:pl-[7%]'} w-full pt-20 fixed h-full `}>
        {children}
        </motion.div>
        </isLargeContext.Provider>

      </SessionProvider>
      </body>
    </html>
  )
}

